### ISSUE TITLE
Converting Subsystem to Simulink Function from inside existing Simulink Function

### ISSUE THREAD

**Issue by stephen99scott** [McSCert/Simulink-Module#2]
'Convert Subsystem' functionality is not showing up in the Simulink context menu when trying to convert a subsystem which is located inside of an existing Simulink Function.

**Comment by monikajaskolka** [comment]
This is probably due to the fact that the `Simulink-Module/src/Utility/` folder does not contain the utility files. These files still need to be migrated to GitHub and are currently only on the SVN repo. These are files that are common across all of our tools, so I think they need to be stored in a submodule.

**Comment by stephen99scott** [comment]
I believe it was due to the conditional logic in getSLModuleTool (sl_customization.m).

The 'Convert Subsystem' schema was only being called if none of the selected blocks were Simulink Functions; however, when selecting a block inside of a Simulink Function, any(selectedFcns) would be true, causing the code not to reach the elseif for the 'Convert Subsystem' functionality.

https://github.com/McSCert/Simulink-Module/blob/e59dbd0b5bf87321aaf22efa2c98425291e012d0/src/sl_customization.m#L12-L21

I added this commit which should fix this issue.
https://github.com/McSCert/Simulink-Module/commit/0f1f7b1be0f5e1382816d70b87bd7b87a8df7b7e
